### PR TITLE
consolidate secrets buckets

### PR DESCRIPTION
**Pull request by timothy-spencer**

### CODE REVIEW

**Comment by timothy-spencer** [comment]
Well, secrets-bucket-* wasn't in credentials.example.yml at all, so thus my sed did not have anything to operate on.  I added the secret there, but no clue why it wasn't there already.

**Comment by rogeruiz** [comment]
looks like it was named something else. 🤦‍♂️ 

`cdn-broker-bucket-*`

https://github.com/18F/cf-domain-broker-alb/blob/master/ci/credentials.example.yml#L13-L26

**Comment by rogeruiz** [comment]
this is already merged, so perhaps another PR with those changes is in order. Tech debt or die.

**Comment by rogeruiz** [comment]
also, in the future ones, it might make sense to `ack`/`grep` for `bucket-`. That's how I found those.

**Comment by jontours** [comment]
I'm currently deleting the old unused files in s3 now to help with credhub work.

**Pull request merged**
